### ISSUE TITLE
Initial deployment of web process fails due to missing rss-output-files directory

### ISSUE THREAD

**Issue by philbudne** [mediacloud/backup-rss-fetcher#24]
```
=====> Start of pbudne-rss-fetcher container output (web.1)
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
           return _run_code(code, main_globals, None,
         File "/app/.heroku/python/lib/python3.10/runpy.py", line 86, in _run_code
           exec(code, run_globals)
         File "/app/scripts/server.py", line 13, in <module>
           import server
         File "/app/server/__init__.py", line 37, in <module>
           Mount("/api/rss", StaticFiles(directory=OUTPUT_RSS_DIR)),
         File "/app/.heroku/python/lib/python3.10/site-packages/starlette/staticfiles.py", line 55, in __init__
           raise RuntimeError(f"Directory '{directory}' does not exist")
       RuntimeError: Directory '/app/storage/rss-output-files' does not exist
       2023/10/15 01:23:20 signal: terminated
```

**Comment by philbudne** [comment]
Addressed in https://github.com/mediacloud/rss-fetcher/commit/f23e2422dd2e3173649f59c8884144093ee9578d
